spring:
  config:
    active:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://travel-with-me-database.ch3tlnexd7aj.ap-northeast-2.rds.amazonaws.com:3306/twm?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul
    username: admin
    password: travelwithme1234
  redis:
    host: localhost
    port: 6380
    maxmemory: 128M

